[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  # Python functions for FastAPI
  api.py:
    runtime = "python3.11"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
